package com.match.app

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.util.Log
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.biometric.BiometricManager
import androidx.biometric.BiometricManager.Authenticators.BIOMETRIC_STRONG
import androidx.biometric.BiometricManager.Authenticators.DEVICE_CREDENTIAL
import androidx.biometric.BiometricPrompt
import androidx.core.content.ContextCompat
import androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen
import androidx.fragment.app.FragmentActivity
import androidx.lifecycle.lifecycleScope
import com.match.app.core.config.RemoteConfigManager
import com.match.app.core.update.InAppUpdateManager
import com.match.app.data.billing.PlayBillingManager
import com.match.app.data.repo.PresenceRepository
import com.match.app.data.session.SessionStore
import com.match.app.ui.MatchRoot
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import javax.inject.Inject

@AndroidEntryPoint
class MainActivity : FragmentActivity() {

    @Inject lateinit var session: SessionStore
    @Inject lateinit var playBilling: PlayBillingManager
    @Inject lateinit var inAppUpdateManager: InAppUpdateManager
    @Inject lateinit var remoteConfig: RemoteConfigManager
    @Inject lateinit var presenceRepository: PresenceRepository

    private var isPermissionPromptInFlight = false
    private var isBiometricPromptShowing = false
    private var presenceJob: Job? = null
    private val requestNotificationPermission = registerForActivityResult(ActivityResultContracts.RequestPermission()) { isPermissionPromptInFlight = false }

    var pendingDeepLink: String? = null
        private set
    fun consumeDeepLink(): String? = pendingDeepLink.also { pendingDeepLink = null }

    private var isReady = false

    override fun onCreate(savedInstanceState: Bundle?) {
        val splash = installSplashScreen()
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        splash.setKeepOnScreenCondition { !isReady }
        lifecycleScope.launch {
            try { kotlinx.coroutines.withTimeout(500) { session.userId.first() } } catch (_: Exception) {}
            isReady = true
        }
        requestNotificationPermissionIfNeeded()
        handleIntent(intent)
        setContent { MatchRoot() }
    }

    override fun onResume() {
        super.onResume()
        if (isPermissionPromptInFlight || isBiometricPromptShowing) return
        lifecycleScope.launch { session.touchActivity() }
        startPresenceHeartbeat()
        lifecycleScope.launch { if (session.biometricLock.first()) showBiometricPrompt() }
        playBilling.connect()
        inAppUpdateManager.checkForUpdate(activity = this, forceUpdateVersionCode = remoteConfig.forceUpdateVersionCode)
    }

    override fun onPause() {
        presenceJob?.cancel()
        presenceJob = null
        super.onPause()
    }

    private fun startPresenceHeartbeat() {
        if (presenceJob?.isActive == true) return
        presenceJob = lifecycleScope.launch {
            while (isActive) {
                presenceRepository.heartbeat()
                delay(PRESENCE_HEARTBEAT_INTERVAL_MS)
            }
        }
    }

    private fun showBiometricPrompt() {
        if (isPermissionPromptInFlight || isBiometricPromptShowing) return
        if (BiometricManager.from(this).canAuthenticate(BIOMETRIC_STRONG or DEVICE_CREDENTIAL) != BiometricManager.BIOMETRIC_SUCCESS) return
        isBiometricPromptShowing = true
        val prompt = BiometricPrompt(this, ContextCompat.getMainExecutor(this), object : BiometricPrompt.AuthenticationCallback() {
            override fun onAuthenticationError(code: Int, msg: CharSequence) {
                isBiometricPromptShowing = false
                if (code == BiometricPrompt.ERROR_USER_CANCELED || code == BiometricPrompt.ERROR_NEGATIVE_BUTTON) finishAffinity()
            }
            override fun onAuthenticationSucceeded(result: BiometricPrompt.AuthenticationResult) { isBiometricPromptShowing = false }
        })
        prompt.authenticate(BiometricPrompt.PromptInfo.Builder()
            .setTitle("Unlock MatrimonyConnect")
            .setSubtitle("Verify your identity to continue")
            .setAllowedAuthenticators(BIOMETRIC_STRONG or DEVICE_CREDENTIAL)
            .build())
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        handleIntent(intent)
    }

    private fun handleIntent(intent: Intent?) {
        val uri = intent?.data
        if (uri == null) {
            // These extras are generated by our immutable notification PendingIntents. Route
            // arguments still use typed positive local ids, while the destination repositories
            // re-authorize profile/chat data before exposing remote content.
            val type = intent?.getStringExtra("notif_type")
            val fromUserId = intent?.getLongExtra("from_user_id", -1L).takeIf { it != null && it > 0 }
            val chatPeerId = intent?.getLongExtra("peer_id", -1L).takeIf { it != null && it > 0 }
            pendingDeepLink = when (type) {
                "message" -> chatPeerId?.let { "chat/$it" } ?: "chat_list"
                "interest_received" -> fromUserId?.let { "detail/$it" } ?: "interests"
                "new_match", "mutual_match" -> fromUserId?.let { "detail/$it" } ?: "matches"
                "profile_viewed" -> "who_viewed"
                "profile_incomplete" -> "profile"
                "inactivity_nudge" -> "matches"
                "like" -> "interests"
                "notification", "reward" -> "notifications"
                "boost_expiring", "subscription_expiry" -> "pricing"
                "verification", "verification_update" -> "verification"
                else -> null
            }
            return
        }

        // Only accept the documented custom scheme. Never concatenate arbitrary URI text into a
        // Navigation route: malformed path values can otherwise bypass typed route assumptions or
        // crash argument parsing. External profile/chat links currently use a positive local id;
        // profile/chat repositories remain the authorization boundary for the destination data.
        if (!uri.scheme.equals(DEEP_LINK_SCHEME, ignoreCase = true) || uri.userInfo != null) {
            rejectDeepLink(uri.toString())
            return
        }

        val host = uri.host?.lowercase()
        val segments = uri.pathSegments
        val hasUnexpectedExtras = !uri.query.isNullOrBlank() || !uri.fragment.isNullOrBlank()

        pendingDeepLink = when (host) {
            "match", "chat" -> {
                if (hasUnexpectedExtras || segments.size != 1) null
                else segments.single().toLongOrNull()?.takeIf { it > 0 }?.let { id ->
                    if (host == "match") "detail/$id" else "chat/$id"
                }
            }
            "notifications" -> staticRouteOrNull(segments, hasUnexpectedExtras, "notifications")
            "interests" -> staticRouteOrNull(segments, hasUnexpectedExtras, "interests")
            "matches" -> staticRouteOrNull(segments, hasUnexpectedExtras, "matches")
            "who_viewed" -> staticRouteOrNull(segments, hasUnexpectedExtras, "who_viewed")
            "pricing" -> staticRouteOrNull(segments, hasUnexpectedExtras, "pricing")
            else -> null
        }

        if (pendingDeepLink == null) rejectDeepLink(uri.toString())
    }

    private fun staticRouteOrNull(segments: List<String>, hasUnexpectedExtras: Boolean, route: String): String? =
        route.takeIf { segments.isEmpty() && !hasUnexpectedExtras }

    private fun rejectDeepLink(raw: String) {
        pendingDeepLink = null
        Log.w("MainActivity", "Rejected malformed or unsupported deep link: ${raw.take(160)}")
    }

    private fun requestNotificationPermissionIfNeeded() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU &&
            ContextCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
            isPermissionPromptInFlight = true
            requestNotificationPermission.launch(Manifest.permission.POST_NOTIFICATIONS)
        }
    }

    private companion object {
        const val PRESENCE_HEARTBEAT_INTERVAL_MS = 2L * 60L * 1000L
        const val DEEP_LINK_SCHEME = "matrimonyconnect"
    }
}
