package com.match.app.domain.model

/** What the user is. */
enum class Gender { MALE, FEMALE, OTHER }

/** What the user wants (can be ANY). */
enum class LookingFor { MALE, FEMALE, ANY }

data class UserProfile(
    val id: Long,
    val firebaseUid: String = "",
    val email: String,
    val displayName: String,
    val age: Int,
    val gender: Gender,
    val lookingFor: LookingFor,
    val city: String,
    val bio: String,
    val rasi: String,
    val nakshatra: String,
    val hasQuestionnaire: Boolean,
    val primaryPhotoPath: String? = null,
    val religion: String = "Hindu",
    val caste: String = "",
    val motherTongue: String = "Telugu",
    val education: String = "Graduate",
    val profession: String = "Software Engineer",
    val maritalStatus: String = "Never Married",
    val heightCm: Int = 165,
    val isVerified: Boolean = false,
    val isPremium: Boolean = false,
    val state: String = "",
    val subCaste: String = "",
    val gothra: String = "",
    val incomeBand: String = "",
    val diet: String = "",
    val familyType: String = "",
    val fatherOccupation: String = "",
    val motherOccupation: String = "",
    val siblings: Int = 0,
    val smoking: String = "",
    val drinking: String = "",
    val personalityType: String = "",
    val hobbies: List<String> = emptyList(),
    val spokenLanguages: List<String> = emptyList(),
    val videoUrl: String = "",
    val residentialStatus: String = "",
    val hasChildren: Boolean = false,
    val profileViewCount: Int = 0,
    val nativeState: String = "",
    val countryOfResidence: String = "",
    val visaStatus: String = "",
    val willingToRelocate: Boolean = false,
    val createdAt: Long = 0L,
    val lastActiveAt: Long = 0L,
    val phoneNumber: String = "",
    val isIncognito: Boolean = false,
    val familyValues: String = "",
    val aboutFamily: String = "",
    val manglik: String = "",
    val dateOfBirth: String = "",
    val weight: Float = 0f,
    val complexion: String = "",
    val physicalStatus: String = "",
    val birthTime: String = "",
    val birthPlace: String = "",
    val familyStatus: String = "",
    val educationField: String = "",
    val institution: String = "",
    val graduationYear: Int = 0,
    val occupationCategory: String = "",
    val employer: String = "",
    val employerType: String = "",
    val citizenship: String = "",
    val isNRI: Boolean = false,
    val fitnessActivities: String = "",
    val matrimonyId: String = "",
    val photoUrl: String = "",
    val voiceBioUrl: String = "",
    val selfVector: FloatArray? = null,
    val partnerVector: FloatArray? = null,
    val profileCompleteness: Float = 0f,
    val verificationLevel: Int = 0,
    val stealthMode: Boolean = false,
    val showLastActive: Boolean = true,
    val showHoroscope: Boolean = true,
    val incomeDisclosure: String = "range",
    val subscriptionPlan: String = "FREE",
    val subscriptionExpiry: Long = 0L,
    val matchScore: Float = 0f,
    val username: String = ""
)

data class MatchResult(
    val user: UserProfile,
    val questionnaireScore: Float,
    val astrologyScore: Float,
    val combinedScore: Float,
    val mode: MatchMode
) {
    val displayScore: Int get() = (primary() * 100f).toInt()
    fun primary(): Float = when (mode) {
        MatchMode.QUESTIONNAIRE -> questionnaireScore
        MatchMode.ASTROLOGY     -> astrologyScore
        MatchMode.ADVANCED      -> combinedScore
    }
}

enum class MatchMode { QUESTIONNAIRE, ASTROLOGY, ADVANCED }

data class MatchFilter(
    val ageMin: Int = 18,
    val ageMax: Int = 70,
    val city: String = "",
    val state: String = "",
    val caste: String = "",
    val minScore: Float = 0f,
    val religion: String = "",
    val motherTongue: String = "",
    val maritalStatus: String = "",
    val verifiedOnly: Boolean = false,
    val incomeMin: String = "",
    val incomeMax: String = "",
    val educationLevel: String = "",
    val diet: String = "",
    val residentialStatus: String = "",
    val hasChildren: String = "",
    val keyword: String = "",
    val gothra: String = "",
    val nativeState: String = "",
    val countryOfResidence: String = "",
    val nriOnly: Boolean = false,
    val willingToRelocate: Boolean = false,
    val recentlyJoinedDays: Int = 0,
    val smoking: String = "",
    val drinking: String = "",
    val familyType: String = "",
    val familyStatus: String = "",
    val physicalStatus: String = "",
    val hasChildrenFilter: String = "",
    val citizenship: String = "",
    val nriStatus: String = "",
    val educationField: String = "",
    val occupationCategory: String = "",
    val employerType: String = "",
    val subCaste: String = "",
    val nakshatra: String = "",
    val rasi: String = "",
    val manglik: String = "",
    val hobbies: String = "",
    val withPhotoOnly: Boolean = true,
    val verifiedLevel: Int = 0,
    val premiumOnly: Boolean = false,
    val lastActiveWithinDays: Int = 0,
    val minPoruthamScore: Int = 0,
    val hasHoroscope: String = ""
)
