#!/usr/bin/env python3
from __future__ import annotations

import re
import zipfile
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
OUT = ROOT / "analysis" / "03-docs-phased-analysis.md"

KEYWORDS = {
    "auth": ["otp", "login", "authentication", "jwt", "password"],
    "onboarding": ["onboarding", "profile completion", "step"],
    "matching": ["match", "compatibility", "recommendation", "search"],
    "realtime": ["chat", "socket", "realtime", "call", "notification"],
    "monetization": ["subscription", "pricing", "payment", "premium", "plan"],
    "trust_safety": ["verification", "moderation", "report", "privacy", "block"],
    "architecture": ["architecture", "scalability", "queue", "cache", "redis", "worker"],
}


def extract_docx_text(path: Path) -> str:
    with zipfile.ZipFile(path) as zf:
        xml = zf.read("word/document.xml").decode("utf-8", errors="ignore")
    chunks = re.findall(r"<w:t[^>]*>(.*?)</w:t>", xml)
    cleaned = []
    for c in chunks:
        t = unescape(c)
        t = re.sub(r"<[^>]+>", " ", t)
        t = re.sub(r"\s+", " ", t).strip()
        if t:
            cleaned.append(t)
    return "\n".join(cleaned)


def extract_pdf_text_best_effort(path: Path) -> str:
    data = path.read_bytes().decode("latin-1", errors="ignore")
    literal = re.findall(r"\(([^\)]{4,})\)", data)
    literal = [re.sub(r"\\[nrt]", " ", s) for s in literal]
    literal = [re.sub(r"\s+", " ", s).strip() for s in literal if re.search(r"[A-Za-z]", s)]
    long_lines = [s for s in literal if len(s) > 24]
    return "\n".join(long_lines)


def score_topics(text: str) -> dict[str, int]:
    low = text.lower()
    out = {}
    for topic, words in KEYWORDS.items():
        out[topic] = sum(low.count(w) for w in words)
    return out


def summarize(text: str, n: int = 12) -> list[str]:
    lines = [re.sub(r"\s+", " ", ln).strip() for ln in text.splitlines()]
    lines = [ln for ln in lines if len(ln) > 30]
    return lines[:n]


def implementation_actions(topic_scores: dict[str, int]) -> list[str]:
    ordered = [t for t, _ in sorted(topic_scores.items(), key=lambda x: x[1], reverse=True) if _ > 0]
    actions = []
    for t in ordered[:4]:
        if t == "auth":
            actions.append("Validate OTP/login + JWT lifecycle against backend auth middleware and add missing hardening tests.")
        elif t == "onboarding":
            actions.append("Trace onboarding step parity (frontend step-1..5 + backend profile requirements) and close field-level gaps.")
        elif t == "matching":
            actions.append("Review matching/search filters, premium gates, and ranking factors for PRD parity.")
        elif t == "realtime":
            actions.append("Audit chat/call/notification realtime flows and document socket scaling assumptions.")
        elif t == "monetization":
            actions.append("Verify entitlement matrix across subscription plans and enforce route-level checks where missing.")
        elif t == "trust_safety":
            actions.append("Expand moderation, report, block, and verification pipelines with explicit SLA and admin audit trails.")
        elif t == "architecture":
            actions.append("Map architecture constraints to deployment runbook: cache, queue, backup, and observability baselines.")
    return actions or ["Low-text extraction quality; perform manual review of source file with dedicated PDF tools."]


def main() -> None:
    docs = sorted([p for p in DOCS_DIR.iterdir() if p.suffix.lower() in {".docx", ".pdf"}])
    md = ["# Docs Phased Analysis (All Files)", "", "Generated by `scripts/docs_phase_analyzer.py`.", ""]

    for i, path in enumerate(docs, 1):
        if path.suffix.lower() == ".docx":
            text = extract_docx_text(path)
            method = "DOCX XML extraction"
        else:
            text = extract_pdf_text_best_effort(path)
            method = "PDF best-effort literal extraction"

        scores = score_topics(text)
        top = ", ".join(f"{k}:{v}" for k, v in sorted(scores.items(), key=lambda x: x[1], reverse=True)[:4])
        snippets = summarize(text, 10)
        actions = implementation_actions(scores)

        md += [f"## File {i:02d}: `{path.name}`", "", f"- Extraction method: {method}", f"- Extracted characters: {len(text)}", f"- Topic signal: {top}", "", "### Phase 1 — Deep Analysis", ""]
        if snippets:
            md += [f"- {s}" for s in snippets]
        else:
            md += ["- No reliable plain-text content extracted."]

        md += ["", "### Phase 2 — Research Synthesis", ""]
        strongest = [k for k, v in sorted(scores.items(), key=lambda x: x[1], reverse=True)[:3]]
        md.append(f"- Dominant requirement domains inferred: {', '.join(strongest)}.")
        md.append("- Cross-reference with existing implementation docs to validate parity and identify missing acceptance criteria.")

        md += ["", "### Phase 3 — Implementation Plan", ""]
        md += [f"- {a}" for a in actions]
        md += [""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
